# Banking Customer 360 Analytics
## 01 - Data Discovery

Purpose: Inspect the raw banking dataset, identify available tables, understand their size, and prepare for data relationship and quality analysis.

## 1. Load and Inspect the Raw Dataset

Load the Excel workbook and identify all available tables.

In [1]:
import pandas as pd

file_path = "../data/raw/banking_customer360_synthetic.xlsx"

excel_file = pd.ExcelFile(file_path)
excel_file.sheet_names

sheets = pd.read_excel(
    file_path,
    sheet_name = None
)
sheets.keys()

for sheet_name, df in sheets.items():
    print(f"{sheet_name}: {df.shape}")

Customers: (5000, 26)
Accounts: (7500, 6)
Transactions: (100000, 7)
Loans: (2500, 7)
Customer_Service: (10000, 6)
Data_Dictionary: (18, 4)

### Initial Findings

The dataset contains six related tables:
Customers, Accounts, Transactions, Loans, Customer_Service, and Data_Dictionary.

Next, we will inspect the Data Dictionary and identify the key fields and relationships between these tables.

## 2. Data Dictionary

Inspect the field definitions provided with the dataset to understand the meaning of the columns before cleaning and integrating the tables.

In [2]:
data_dictionary = sheets["Data_Dictionary"]
data_dictionary

,table,column,meaning,type
0,customers,customer_id,Unique customer identifier,Key
1,customers,annual_income,Estimated annual income,Numeric
2,customers,credit_score,Creditworthiness score,Numeric
3,customers,churn,"1 = churned, 0 = retained",Target
4,accounts,account_id,Unique account identifier,Key
5,accounts,customer_id,Customer owning the account,Foreign Key
6,transactions,transaction_id,Unique transaction identifier,Key
7,transactions,customer_id,Customer performing transaction,Foreign Key
8,transactions,amount,Transaction amount,Numeric
9,transactions,channel,Transaction channel,Categorical
10,loans,loan_id,Unique loan identifier,Key
11,loans,customer_id,Borrowing customer,Foreign Key
12,loans,loan_amount,Loan principal,Numeric
13,loans,repayment_status,Loan repayment condition,Categorical
14,customer_service,interaction_id,Unique service interaction,Key
15,customer_service,customer_id,Customer involved in interaction,Foreign Key
16,customer_service,complaint_type,Type of customer complaint,Categorical
17,customer_service,resolution_status,Service resolution state,Categorical

In [3]:
data_dictionary.columns

Index(['table', 'column', 'meaning', 'type'], dtype='str')

In [4]:
data_dictionary.head(20)

,table,column,meaning,type
0,customers,customer_id,Unique customer identifier,Key
1,customers,annual_income,Estimated annual income,Numeric
2,customers,credit_score,Creditworthiness score,Numeric
3,customers,churn,"1 = churned, 0 = retained",Target
4,accounts,account_id,Unique account identifier,Key
5,accounts,customer_id,Customer owning the account,Foreign Key
6,transactions,transaction_id,Unique transaction identifier,Key
7,transactions,customer_id,Customer performing transaction,Foreign Key
8,transactions,amount,Transaction amount,Numeric
9,transactions,channel,Transaction channel,Categorical
10,loans,loan_id,Unique loan identifier,Key
11,loans,customer_id,Borrowing customer,Foreign Key
12,loans,loan_amount,Loan principal,Numeric
13,loans,repayment_status,Loan repayment condition,Categorical
14,customer_service,interaction_id,Unique service interaction,Key
15,customer_service,customer_id,Customer involved in interaction,Foreign Key
16,customer_service,complaint_type,Type of customer complaint,Categorical
17,customer_service,resolution_status,Service resolution state,Categorical

## 3. Table Structure

Review the columns in each table to identify customer IDs, account IDs, transaction fields, loan fields, and service-related fields.

In [7]:
for sheet_name, df in sheets.items():
    print(f"\n{'=' * 60}")
    print(f"{sheet_name}")
    print(f"{'=' * 60}")
    print(df.columns.tolist())

============================================================
Customers
============================================================
['customer_id', 'age', 'gender', 'country', 'occupation', 'annual_income', 'credit_score', 'tenure_years', 'join_date', 'total_transactions', 'total_transaction_value', 'avg_transaction_value', 'last_transaction_date', 'loan_count', 'total_loan_amount', 'late_loan_count', 'default_loan_count', 'complaint_count', 'escalated_count', 'account_count', 'total_balance', 'active_account_count', 'recency_days', 'products_number', 'churn', 'loan_to_income_ratio']

============================================================
Accounts
============================================================
['account_id', 'customer_id', 'account_type', 'opening_date', 'status', 'balance']

============================================================
Transactions
============================================================
['transaction_id', 'customer_id', 'account_id', 'transaction_date', 'transaction_type', 'amount', 'channel']

============================================================
Loans
============================================================
['loan_id', 'customer_id', 'loan_type', 'loan_amount', 'interest_rate', 'start_date', 'repayment_status']

============================================================
Customer_Service
============================================================
['interaction_id', 'customer_id', 'interaction_date', 'complaint_type', 'resolution_status', 'resolution_days']

============================================================
Data_Dictionary
============================================================
['table', 'column', 'meaning', 'type']

## 4. Data Types

Review the data types of each column to identify numeric, text, date, and other fields that may require cleaning or transformation.

In [8]:
for sheet_name, df in sheets.items():
    print(f"\n{'=' * 60}")
    print(f"{sheet_name}")
    print(f"{'=' * 60}")
    print(df.dtypes)

============================================================
Customers
============================================================
customer_id                           str
age                                 int64
gender                                str
country                               str
occupation                            str
annual_income                       int64
credit_score                        int64
tenure_years                        int64
join_date                  datetime64[us]
total_transactions                  int64
total_transaction_value           float64
avg_transaction_value             float64
last_transaction_date      datetime64[us]
loan_count                          int64
total_loan_amount                 float64
late_loan_count                     int64
default_loan_count                  int64
complaint_count                     int64
escalated_count                     int64
account_count                       int64
total_balance                     float64
active_account_count                int64
recency_days                        int64
products_number                     int64
churn                               int64
loan_to_income_ratio              float64
dtype: object

============================================================
Accounts
============================================================
account_id                 str
customer_id                str
account_type               str
opening_date    datetime64[us]
status                     str
balance                float64
dtype: object

============================================================
Transactions
============================================================
transaction_id                 str
customer_id                    str
account_id                     str
transaction_date    datetime64[us]
transaction_type               str
amount                     float64
channel                        str
dtype: object

============================================================
Loans
============================================================
loan_id                        str
customer_id                    str
loan_type                      str
loan_amount                float64
interest_rate              float64
start_date          datetime64[us]
repayment_status               str
dtype: object

============================================================
Customer_Service
============================================================
interaction_id                  str
customer_id                     str
interaction_date     datetime64[us]
complaint_type                  str
resolution_status               str
resolution_days               int64
dtype: object

============================================================
Data_Dictionary
============================================================
table      str
column     str
meaning    str
type       str
dtype: object

## 5. Missing Values

Check the number of missing values in each table as part of the initial data quality assessment.

In [9]:
for sheet_name, df in sheets.items():
    print(f"\n{'=' * 60}")
    print(f"{sheet_name}")
    print(f"{'=' * 60}")
    print(df.isnull().sum())

============================================================
Customers
============================================================
customer_id                0
age                        0
gender                     0
country                    0
occupation                 0
annual_income              0
credit_score               0
tenure_years               0
join_date                  0
total_transactions         0
total_transaction_value    0
avg_transaction_value      0
last_transaction_date      0
loan_count                 0
total_loan_amount          0
late_loan_count            0
default_loan_count         0
complaint_count            0
escalated_count            0
account_count              0
total_balance              0
active_account_count       0
recency_days               0
products_number            0
churn                      0
loan_to_income_ratio       0
dtype: int64

============================================================
Accounts
============================================================
account_id      0
customer_id     0
account_type    0
opening_date    0
status          0
balance         0
dtype: int64

============================================================
Transactions
============================================================
transaction_id          0
customer_id             0
account_id          22593
transaction_date        0
transaction_type        0
amount                  0
channel                 0
dtype: int64

============================================================
Loans
============================================================
loan_id             0
customer_id         0
loan_type           0
loan_amount         0
interest_rate       0
start_date          0
repayment_status    0
dtype: int64

============================================================
Customer_Service
============================================================
interaction_id       0
customer_id          0
interaction_date     0
complaint_type       0
resolution_status    0
resolution_days      0
dtype: int64

============================================================
Data_Dictionary
============================================================
table      0
column     0
meaning    0
type       0
dtype: int64

## 6. Duplicate Records

Check for duplicate rows in each table before data cleaning.

In [10]:
for sheet_name, df in sheets.items():
    print(f"{sheet_name}: {df.duplicated().sum()} duplicate rows")

Customers: 0 duplicate rows
Accounts: 0 duplicate rows
Transactions: 0 duplicate rows
Loans: 0 duplicate rows
Customer_Service: 0 duplicate rows
Data_Dictionary: 0 duplicate rows

## 7. Sample Records

Review a small sample of each table to understand the actual values stored in the dataset.

In [11]:
for sheet_name, df in sheets.items():
    print(f"\n{'=' * 60}")
    print(f"{sheet_name}")
    print(f"{'=' * 60}")
    display(df.head(3))

============================================================
Customers
============================================================

,customer_id,age,gender,country,occupation,annual_income,credit_score,tenure_years,join_date,total_transactions,...,default_loan_count,complaint_count,escalated_count,account_count,total_balance,active_account_count,recency_days,products_number,churn,loan_to_income_ratio
0,C00001,25,Male,France,Salaried,25700,577,7,2025-02-22,22,...,0,1,0,4,337661.45,4,6,4,0,0.00
1,C00002,59,Male,Germany,Salaried,99800,682,12,2021-08-05,21,...,0,2,0,1,20846.07,1,13,1,0,0.00
2,C00003,53,Female,Spain,Salaried,102200,786,11,2016-06-20,16,...,0,1,0,2,46466.48,2,12,3,0,2.57

============================================================
Accounts
============================================================

  account_id customer_id account_type opening_date  status    balance
0    A000001      C00850      Savings   2021-11-10  Active   66553.46
1    A000002      C04939      Savings   2019-08-09  Active   46617.82
2    A000003      C02706      Savings   2023-05-04  Active  155264.40

============================================================
Transactions
============================================================

,transaction_id,customer_id,account_id,transaction_date,transaction_type,amount,channel
0,T0000001,C04694,A001801,2025-11-16,Transfer,192.74,Branch
1,T0000002,C02033,A005896,2025-05-06,Deposit,103.74,Mobile
2,T0000003,C02183,A003026,2025-11-23,Withdrawal,580.70,ATM

============================================================
Loans
============================================================

,loan_id,customer_id,loan_type,loan_amount,interest_rate,start_date,repayment_status
0,L000001,C02898,Personal,101707.17,8.91,2022-08-13,On Time
1,L000002,C03427,Personal,35250.03,12.80,2025-07-18,On Time
2,L000003,C02664,Personal,60192.72,8.34,2020-10-07,On Time

============================================================
Customer_Service
============================================================

,interaction_id,customer_id,interaction_date,complaint_type,resolution_status,resolution_days
0,S000001,C00301,2025-03-02,Transaction Issue,Resolved,7
1,S000002,C00351,2025-07-08,Other,Resolved,13
2,S000003,C02715,2025-01-09,Transaction Issue,Resolved,11

============================================================
Data_Dictionary
============================================================

       table         column                     meaning     type
0  customers    customer_id  Unique customer identifier      Key
1  customers  annual_income     Estimated annual income  Numeric
2  customers   credit_score      Creditworthiness score  Numeric

## 8. Identify Key Fields

Inspect columns containing ID fields to identify possible primary keys and foreign keys for the Customer 360 data model.

In [12]:
for sheet_name, df in sheets.items():
    id_columns = [
        col for col in df.columns
        if "id" in col.lower()
    ]
    
    print(f"{sheet_name}: {id_columns}")

Customers: ['customer_id']
Accounts: ['account_id', 'customer_id']
Transactions: ['transaction_id', 'customer_id', 'account_id']
Loans: ['loan_id', 'customer_id']
Customer_Service: ['interaction_id', 'customer_id']
Data_Dictionary: []

## 9. Key Uniqueness Check

Check whether candidate ID fields contain unique values. This helps identify primary keys and fields used to connect related tables.

In [13]:
for sheet_name, df in sheets.items():
    id_columns = [
        col for col in df.columns
        if "id" in col.lower()
    ]
    
    print(f"\n{sheet_name}")
    
    for col in id_columns:
        print(
            f"{col}: "
            f"{df[col].nunique()} unique / "
            f"{len(df)} total"
        )

Customers
customer_id: 5000 unique / 5000 total

Accounts
account_id: 7500 unique / 7500 total
customer_id: 3878 unique / 7500 total

Transactions
transaction_id: 100000 unique / 100000 total
customer_id: 5000 unique / 100000 total
account_id: 7481 unique / 100000 total

Loans
loan_id: 2500 unique / 2500 total
customer_id: 1962 unique / 2500 total

Customer_Service
interaction_id: 10000 unique / 10000 total
customer_id: 4303 unique / 10000 total

Data_Dictionary

## 10. Table Relationships

Compare ID fields across tables to identify how customers, accounts, transactions, loans, and service interactions are connected.

In [14]:
id_values = {}

for sheet_name, df in sheets.items():
    id_values[sheet_name] = {
        col: set(df[col].dropna().unique())
        for col in df.columns
        if "id" in col.lower()
    }

for sheet_name, columns in id_values.items():
    print(f"\n{'=' * 60}")
    print(sheet_name)
    print(f"{'=' * 60}")
    
    for col, values in columns.items():
        print(f"{col}: {len(values)} unique values")

============================================================
Customers
============================================================
customer_id: 5000 unique values

============================================================
Accounts
============================================================
account_id: 7500 unique values
customer_id: 3878 unique values

============================================================
Transactions
============================================================
transaction_id: 100000 unique values
customer_id: 5000 unique values
account_id: 7481 unique values

============================================================
Loans
============================================================
loan_id: 2500 unique values
customer_id: 1962 unique values

============================================================
Customer_Service
============================================================
interaction_id: 10000 unique values
customer_id: 4303 unique values

============================================================
Data_Dictionary
============================================================

## 11. Data Discovery Summary

Create a compact summary of the structure and data quality of all tables.

In [15]:
discovery_summary = []

for sheet_name, df in sheets.items():
    discovery_summary.append({
        "Table": sheet_name,
        "Rows": df.shape[0],
        "Columns": df.shape[1],
        "Duplicate_Rows": df.duplicated().sum(),
        "Missing_Values": df.isnull().sum().sum()
    })

discovery_summary = pd.DataFrame(discovery_summary)

discovery_summary

              Table    Rows  Columns  Duplicate_Rows  Missing_Values
0         Customers    5000       26               0               0
1          Accounts    7500        6               0               0
2      Transactions  100000        7               0           22593
3             Loans    2500        7               0               0
4  Customer_Service   10000        6               0               0
5   Data_Dictionary      18        4               0               0

## 12. Data Discovery Findings

The raw dataset contains six related tables covering customers, accounts, transactions, loans, customer service interactions, and field definitions.

The initial inspection covers table size, columns, data types, missing values, duplicate records, candidate ID fields, and possible relationships.

The next stage will use these findings to define the data model and determine how the tables should be cleaned and integrated into a Customer 360 dataset.

01_data_discovery.ipynb

1. Title + Purpose
   ↓
2. Load and Inspect Raw Dataset
   ↓
3. Initial Findings
   ↓
4. Data Dictionary
   ↓
5. Table Structure
   ↓
6. Data Types
   ↓
7. Missing Values
   ↓
8. Duplicate Records
   ↓
9. Sample Records
   ↓
10. Identify Key Fields
   ↓
11. Key Uniqueness Check
   ↓
12. Table Relationships
   ↓
13. Data Discovery Summary
   ↓
14. Final Findings

## 13. Identify Table Relationships

Identify the ID fields that connect the banking tables.

In [16]:
for sheet_name, df in sheets.items():
    print(f"\n{sheet_name}")
    print("-"*50)

    for col in df.columns:
        if "id" in col.lower():
            print(col)

Customers
--------------------------------------------------
customer_id

Accounts
--------------------------------------------------
account_id
customer_id

Transactions
--------------------------------------------------
transaction_id
customer_id
account_id

Loans
--------------------------------------------------
loan_id
customer_id

Customer_Service
--------------------------------------------------
interaction_id
customer_id

Data_Dictionary
--------------------------------------------------

## Final Data Model

The dataset is centered on `customer_id`.

Customers connect to Accounts, Transactions, Loans, and Customer_Service. Accounts connect to Transactions through `account_id`.

This relationship structure will be used to build the Customer 360 dataset.

In [ ]:
|